version: '3.1'
services:
  app:
    container_name: app-springboot-postgresql
    image: main_image
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=calculator